// Daily inspirational quotes — rotates based on day of year
const QUOTES = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Your work is going to fill a large part of your life. Make it count.", author: "Steve Jobs" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Excellence is not a skill. It's an attitude.", author: "Ralph Marston" },
  { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Great things never come from comfort zones.", author: "Anonymous" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Anonymous" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
  { text: "Dream it. Wish it. Do it.", author: "Anonymous" },
  { text: "If you want to achieve greatness, stop asking for permission.", author: "Anonymous" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "A little progress each day adds up to big results.", author: "Satya Nani" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Be the spark that lights someone else's day.", author: "Anonymous" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Go the extra mile. It's never crowded.", author: "Wayne Dyer" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "Hustle until your haters ask if you're hiring.", author: "Anonymous" },
  { text: "Be stronger than your excuses.", author: "Anonymous" },
  { text: "Nothing worth having comes easy.", author: "Theodore Roosevelt" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Every day is a new beginning. Take a deep breath and start again.", author: "Anonymous" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
];

export function getDailyQuote(): { text: string; author: string } {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000);
  return QUOTES[dayOfYear % QUOTES.length];
}
