name = "butcher-storefront"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "pnpm install --shamefully-hoist && cd apps/storefront && pnpm run build:cf"
